import { OmGioCharacter, Project, ProjectStats, ProjectQualityCheck } from '../types';

export const OM_GIO_DEFAULT_CHARACTER: OmGioCharacter = {
  id: 'om-gio-primary',
  name: 'Om Gio',
  age: 28,
  gender: 'Male',
  nationality: 'Indonesian',
  bodyType: 'Slim / fit',
  faceShape: 'Oval',
  hair: 'Short black hair, neatly styled',
  eyewear: 'Rectangular eyeglasses',
  facialHair: 'Thin mustache and subtle facial hair',
  skinTone: 'Natural Indonesian skin tone',
  style: 'Photorealistic realistic human',
  identityLock: true,
  identityStrength: '95%',
  sheetAngles: {
    front: 'front-view-portrait',
    leftProfile: 'left-profile-angle',
    rightProfile: 'right-profile-angle',
    threeQuarter: 'three-quarter-hero',
    fullBody: 'full-body-fashion-fit',
    expressions: {
      smile: 'friendly-authentic-smile',
      neutral: 'poised-focus-neutral',
      serious: 'authoritative-tech-serious',
    },
    closeups: {
      glasses: 'matte-black-rectangular-frames',
      mustache: 'precision-trimmed-thin-mustache',
      watch: 'steel-chronograph-black-dial',
      shoes: 'minimalist-white-leather-sneakers',
    },
  },
};

export const ANALYSIS_PIPELINE_STEPS = [
  'Uploading Video...',
  'Analyzing Metadata...',
  'Extracting Frames...',
  'Detecting Shots...',
  'Detecting Scenes...',
  'Analyzing Characters...',
  'Analyzing Body Movement...',
  'Analyzing Facial Expressions...',
  'Analyzing Camera...',
  'Analyzing Environment...',
  'Analyzing Lighting...',
  'Analyzing Wardrobe...',
  'Extracting Audio...',
  'Detecting Speech...',
  'Transcribing Dialogue...',
  'Detecting Speakers...',
  'Mapping Dialogue To Scenes...',
  'Generating Om Gio Prompts...',
  'Checking Continuity...',
  'Checking Missing Dialogue...',
  'Finalizing Project...',
];

export const INITIAL_QUALITY_CHECK: ProjectQualityCheck = {
  characterIdentity: true,
  sceneTiming: true,
  action: true,
  camera: true,
  cameraMovement: true,
  environment: true,
  lighting: true,
  wardrobe: true,
  expression: true,
  dialogue: true,
  dialogueTiming: true,
  speaker: true,
  audio: true,
  continuity: true,
  duration: true,
  aspectRatio: true,
};

export const INITIAL_PROJECT_STATS: ProjectStats = {
  totalDuration: 84,
  totalDurationStr: '00:01:24',
  speechDuration: 76,
  speechDurationStr: '00:01:16',
  speakerCount: 1,
  dialogueCount: 8,
  wordCount: 184,
  unclearCount: 0,
  unmappedCount: 0,
  sceneCount: 6,
  promptsGeneratedCount: 6,
};

// High quality realistic sample project pre-loaded for instant demonstration and testing
export const SAMPLE_PROJECT_TECH_REVIEW: Project = {
  id: 'sample-project-01',
  name: 'Review AI Workflow & Studio Setup (Authorized Source)',
  createdAt: '2026-10-04T08:00:00.000Z',
  updatedAt: '2026-10-04T08:30:00.000Z',
  permissionConfirmed: true,
  recreationMode: 'EXACT RECREATION',
  character: OM_GIO_DEFAULT_CHARACTER,
  identityLockStrength: '95%',
  globalLocks: {
    characterLock: true,
    wardrobeLock: true,
    locationLock: true,
    lightingContinuity: true,
    visualStyleLock: true,
  },
  userBranding: {
    enabled: true,
    brandText: 'OM GIO AI',
    position: 'top-right',
    opacity: 85,
  },
  videoMetadata: {
    filename: 'ai_studio_workflow_omgio_source.mp4',
    duration: 54,
    durationFormatted: '00:00:54',
    width: 1920,
    height: 1080,
    resolutionFormatted: '1920 × 1080',
    fps: 30,
    fileSize: '42.8 MB',
    aspectRatio: '16:9',
    codec: 'H.264 / AVC (High Profile)',
    audioCodec: 'AAC-LC (Stereo, 48.0 kHz)',
    audioChannels: '2 (Stereo)',
    totalFrames: 1620,
    audioDetected: true,
    audioDuration: '00:00:54',
  },
  stats: {
    totalDuration: 54,
    totalDurationStr: '00:00:54',
    speechDuration: 49,
    speechDurationStr: '00:00:49',
    speakerCount: 1,
    dialogueCount: 6,
    wordCount: 142,
    unclearCount: 0,
    unmappedCount: 0,
    sceneCount: 5,
    promptsGeneratedCount: 5,
  },
  qualityCheck: {
    characterIdentity: true,
    sceneTiming: true,
    action: true,
    camera: true,
    cameraMovement: true,
    environment: true,
    lighting: true,
    wardrobe: true,
    expression: true,
    dialogue: true,
    dialogueTiming: true,
    speaker: true,
    audio: true,
    continuity: true,
    duration: true,
    aspectRatio: true,
  },
  missingDialogueWarnings: [],
  transcript: [
    {
      id: 'd-1',
      sceneId: 'sc-1',
      speaker: 'Om Gio',
      speakerOriginal: 'Creator 1',
      startTime: 0.2,
      endTime: 4.8,
      formattedStartTime: '00:00.20',
      formattedEndTime: '00:04.80',
      text: 'Halo teman-teman semua, selamat datang kembali di channel Om Gio AI.',
      confidence: 0.99,
      language: 'Indonesian',
      emotion: 'friendly, welcoming, professional',
      delivery: 'Clear conversational Indonesian, upbeat intro cadence with crisp studio vocal projection',
    },
    {
      id: 'd-2',
      sceneId: 'sc-2',
      speaker: 'Om Gio',
      speakerOriginal: 'Creator 1',
      startTime: 5.4,
      endTime: 14.1,
      formattedStartTime: '00:05.40',
      formattedEndTime: '00:14.10',
      text: 'Hari ini saya akan mendemonstrasikan bagaimana kita bisa menganalisis video sumber frame-by-frame dan merekonstruksi setiap adegan secara otomatis.',
      confidence: 0.98,
      language: 'Indonesian',
      emotion: 'articulate, authoritative, engaging',
      delivery: 'Structured tech presentation pacing, clear emphasis on key technical terminology',
    },
    {
      id: 'd-3',
      sceneId: 'sc-3',
      speaker: 'Om Gio',
      speakerOriginal: 'Creator 1',
      startTime: 14.6,
      endTime: 25.2,
      formattedStartTime: '00:14.60',
      formattedEndTime: '00:25.20',
      text: 'Kunci utamanya ada pada sinkronisasi audio dan dialog lengkap. Kita tidak boleh meringkas ucapan sedikit pun agar hasil lip-sync dan ekspresi di Veo tetap sempurna.',
      confidence: 0.99,
      language: 'Indonesian',
      emotion: 'emphatic, focused, serious',
      delivery: 'Firm articulate instruction, hands gesturing to screen monitor with purposeful emphasis',
    },
    {
      id: 'd-4',
      sceneId: 'sc-4',
      speaker: 'Om Gio',
      speakerOriginal: 'Creator 1',
      startTime: 25.8,
      endTime: 38.3,
      formattedStartTime: '00:25.80',
      formattedEndTime: '00:38.30',
      text: 'Perhatikan bagaimana konsistensi kacamata kotak, gaya rambut, dan proporsi wajah tetap terkunci di angka sembilan puluh lima persen di seluruh scene.',
      confidence: 0.97,
      language: 'Indonesian',
      emotion: 'confident, smiling, proud',
      delivery: 'Subtle friendly smile, leaning in toward camera with direct eye contact',
    },
    {
      id: 'd-5',
      sceneId: 'sc-5',
      speaker: 'Om Gio',
      speakerOriginal: 'Creator 1',
      startTime: 39.0,
      endTime: 53.5,
      formattedStartTime: '00:39.00',
      formattedEndTime: '00:53.50',
      text: 'Cukup salin prompt ini langsung ke Google Flow atau Veo, dan saksikan hasilnya. Jangan lupa like, subscribe, dan kita jumpa di video berikutnya!',
      confidence: 0.99,
      language: 'Indonesian',
      emotion: 'charismatic, warm, energetic outro',
      delivery: 'Warm enthusiastic closing tone, natural farewell wave gesture to camera',
    },
  ],
  audioEvents: [
    {
      id: 'ae-1',
      type: 'dialogue',
      label: 'Spoken Dialogue (Intro)',
      startTime: 0.2,
      endTime: 4.8,
      formattedRange: '00:00.20 — 00:04.80',
      description: 'Main speaker greeting in clear studio acoustic environment.',
      intensity: 'high',
    },
    {
      id: 'ae-2',
      type: 'music',
      label: 'Background Ambient Lo-Fi Synth',
      startTime: 0.0,
      endTime: 54.0,
      formattedRange: '00:00.00 — 00:54.00',
      description: 'Subtle modern tech synth pad sitting at -24dB beneath dialogue.',
      intensity: 'low',
    },
    {
      id: 'ae-3',
      type: 'pause',
      label: 'Breath & Cadence Pause',
      startTime: 4.8,
      endTime: 5.4,
      formattedRange: '00:04.80 — 00:05.40',
      description: 'Natural speaker intake pause before technical segment.',
      intensity: 'low',
    },
    {
      id: 'ae-4',
      type: 'dialogue',
      label: 'Spoken Dialogue (Methodology)',
      startTime: 5.4,
      endTime: 14.1,
      formattedRange: '00:05.40 — 00:14.10',
      description: 'Detailed explanation of automated scene reconstruction.',
      intensity: 'high',
    },
    {
      id: 'ae-5',
      type: 'sfx',
      label: 'Keyboard Tactile Tap',
      startTime: 14.2,
      endTime: 14.5,
      formattedRange: '00:14.20 — 00:14.50',
      description: 'Mechanical switch click from studio desk control.',
      intensity: 'medium',
    },
    {
      id: 'ae-6',
      type: 'dialogue',
      label: 'Spoken Dialogue (Lip-sync emphasis)',
      startTime: 14.6,
      endTime: 25.2,
      formattedRange: '00:14.60 — 00:25.20',
      description: 'Firm instruction regarding unsummarized transcript requirement.',
      intensity: 'high',
    },
    {
      id: 'ae-7',
      type: 'dialogue',
      label: 'Spoken Dialogue (Identity Lock)',
      startTime: 25.8,
      endTime: 38.3,
      formattedRange: '00:25.80 — 00:38.30',
      description: 'Explanation of 95% identity strength and physical traits.',
      intensity: 'high',
    },
    {
      id: 'ae-8',
      type: 'dialogue',
      label: 'Spoken Dialogue (Call to action & outro)',
      startTime: 39.0,
      endTime: 53.5,
      formattedRange: '00:39.00 — 00:53.50',
      description: 'Outro message, subscription reminder, and friendly sign-off.',
      intensity: 'high',
    },
  ],
  scenes: [
    {
      id: 'sc-1',
      sceneNumber: 1,
      sceneLabel: 'SCENE 01',
      startTime: 0,
      endTime: 5,
      timeRangeStr: '00:00 — 00:05',
      durationSeconds: 5,
      durationFormatted: '5.0s',
      thumbnailUrl: '',
      subject: 'Om Gio standing centrally in high-end creator studio facing camera with engaging posture',
      character: 'Om Gio (Indonesian male, 28, slim fit, oval face, rectangular glasses, thin mustache, styled short black hair)',
      action: 'Om Gio smiles warmly at the lens, lifts right hand in a relaxed open-palm welcome gesture, then rests forearm naturally on the ergonomic studio desk.',
      bodyMovement: 'Subtle weight balance shift to left leg, relaxed shoulders, fluid natural arm gesture upward.',
      facialExpression: 'Warm welcoming smile, engaged friendly eyes, natural blinking cadence.',
      eyeDirection: 'Direct center lock on the camera lens.',
      cameraAngle: 'Eye-level, straight-on frontal perspective.',
      cameraDistance: 'Medium shot (waist up).',
      cameraMovement: 'Subtle slow cinematic push-in (0.5m forward tracking).',
      lensFeel: '50mm prime cinematic look, natural perspective, gentle background compression.',
      composition: 'Center-balanced composition with golden ratio headroom.',
      environment: 'Ultra-modern tech creator studio with acoustic dark grey slatted wood panels and vertical cyan LED light channels.',
      background: 'High-end ultrawide monitor displaying code and timeline waveforms softly blurred in depth.',
      lighting: '3-point studio lighting: large softbox key light 45 degrees left, subtle warm fill right, vivid cyan-electric blue rim hair light.',
      colorPalette: 'Charcoal black, deep indigo, electric cyan accent, warm natural skin tones.',
      wardrobe: {
        shirt: 'Fitted charcoal black studio crewneck shirt',
        pants: 'Dark navy tailored slim-fit chinos',
        shoes: 'Minimalist white leather low-top sneakers',
        watch: 'Brushed stainless steel chronograph with black dial',
        glasses: 'Modern matte-black rectangular titanium frames',
        accessories: 'Subtle black wireless lavalier clip on collar',
      },
      props: 'Matte black studio desk, Shure-style dynamic microphone on black boom arm, slim aluminum laptop.',
      interaction: 'Touches desk corner smoothly while greeting viewers.',
      motion: 'Smooth organic 24fps film motion cadence.',
      audioDescription: 'Clean studio acoustics, warm proximity effect on dialogue, gentle lo-fi synth bed at -24dB.',
      dialogueSegments: [
        {
          id: 'd-1',
          sceneId: 'sc-1',
          speaker: 'Om Gio',
          startTime: 0.2,
          endTime: 4.8,
          formattedStartTime: '00:00.20',
          formattedEndTime: '00:04.80',
          text: 'Halo teman-teman semua, selamat datang kembali di channel Om Gio AI.',
          confidence: 0.99,
          language: 'Indonesian',
          emotion: 'friendly, welcoming, professional',
          delivery: 'Clear conversational Indonesian, upbeat intro cadence with crisp studio vocal projection',
        },
      ],
      dialogueTiming: 'Start: 00:00.20 | End: 00:04.80',
      voiceDelivery: 'Upbeat friendly Indonesian creator voice, articulate phrasing, warm resonant tone.',
      lipSyncInstructions: 'Accurate lip synchronization with Indonesian phonemes: Ha-lo te-man te-man se-mu-a... Natural mouth opening and relaxed jaw return.',
      continuityNotes: 'Scene 01 initiates identity baseline. Hair, glasses, watch, and studio layout establish the master continuity reference.',
      visualStyle: 'Photorealistic cinematic video, realistic skin pore texture, natural eye micro-movements, cinematic depth of field.',
      negativeInstructions: [
        'Do not skip dialogue.',
        'Do not summarize dialogue.',
        'Do not paraphrase dialogue.',
        'Do not invent dialogue.',
        'Do not add dialogue.',
        'Do not change the dialogue.',
        'Do not make the character speak during silent sections.',
        'Do not create random voice-over.',
        'Do not change character identity.',
        'Do not morph the face.',
        'Do not distort the face.',
        'Do not distort hands.',
        'Do not create extra fingers.',
        'Do not create extra people.',
        'Do not create unwanted text.',
        'Do not create unwanted logos.',
        'Do not remove third-party watermarks.',
      ],
      generatedPrompt: '',
    },
    {
      id: 'sc-2',
      sceneNumber: 2,
      sceneLabel: 'SCENE 02',
      startTime: 5,
      endTime: 14,
      timeRangeStr: '00:05 — 00:14',
      durationSeconds: 9,
      durationFormatted: '9.0s',
      thumbnailUrl: '',
      subject: 'Om Gio demonstrating the automated frame-by-frame analysis workflow',
      character: 'Om Gio (Indonesian male, 28, slim fit, oval face, rectangular glasses, thin mustache, styled short black hair)',
      action: 'Om Gio turns slightly 25 degrees toward the left workstation display, points with his index finger toward the glowing video timeline, then pivots his gaze back to the camera with an articulate explanatory expression.',
      bodyMovement: 'Torso rotates smoothly to the left, right arm extends toward the monitor, natural wrist pivot, then returns to open gesture.',
      facialExpression: 'Focused, articulate, professional tech authority with subtle enthusiastic brow lift.',
      eyeDirection: 'Looks at the monitor for 3 seconds, then locks eyes back with the camera lens.',
      cameraAngle: 'Medium-close shot, slight 15-degree side angle profile.',
      cameraDistance: 'Medium close-up (chest to top of head).',
      cameraMovement: 'Subtle slow slider truck right to left maintaining steady subject parallax.',
      lensFeel: '85mm portrait prime lens, creamy shallow depth of field isolating Om Gio from background glow.',
      composition: 'Left third rule of thirds composition leaving screen space on the right for studio visuals.',
      environment: 'Ultra-modern tech creator studio with acoustic dark grey slatted wood panels and vertical cyan LED light channels.',
      background: 'Glowing monitor showcasing video waveform timelines and AI prompt cards.',
      lighting: 'Controlled key lighting on face with vivid cyan edge rim light accentuating the jawline and glasses contour.',
      colorPalette: 'Deep navy, slate grey, neon cyan glow, natural warm Indonesian skin tone.',
      wardrobe: {
        shirt: 'Fitted charcoal black studio crewneck shirt',
        pants: 'Dark navy tailored slim-fit chinos',
        shoes: 'Minimalist white leather low-top sneakers',
        watch: 'Brushed stainless steel chronograph with black dial',
        glasses: 'Modern matte-black rectangular titanium frames',
        accessories: 'Subtle black wireless lavalier clip on collar',
      },
      props: 'Ultrawide curved gaming/production monitor, mechanical keyboard with subtle RGB backlight.',
      interaction: 'Points at the screen timeline interface without touching the display surface.',
      motion: 'Precise and confident presenter body dynamics.',
      audioDescription: 'Dialogue prioritized in center channel, subtle keyboard key click in background at 00:14.20.',
      dialogueSegments: [
        {
          id: 'd-2',
          sceneId: 'sc-2',
          speaker: 'Om Gio',
          startTime: 5.4,
          endTime: 14.1,
          formattedStartTime: '00:05.40',
          formattedEndTime: '00:14.10',
          text: 'Hari ini saya akan mendemonstrasikan bagaimana kita bisa menganalisis video sumber frame-by-frame dan merekonstruksi setiap adegan secara otomatis.',
          confidence: 0.98,
          language: 'Indonesian',
          emotion: 'articulate, authoritative, engaging',
          delivery: 'Structured tech presentation pacing, clear emphasis on key technical terminology',
        },
      ],
      dialogueTiming: 'Start: 00:05.40 | End: 00:14.10',
      voiceDelivery: 'Informed, articulate, professional Indonesian cadence with crisp diction on technical terms.',
      lipSyncInstructions: 'Flawless lip sync tracking: Ha-ri i-ni sa-ya a-kan men-de-mon-stra-si-kan... Natural mouth shapes on vowels and closed lips on "m".',
      continuityNotes: 'Continuity matched to Scene 01: identical wardrobe, glasses position, hair parting, and lighting temperature.',
      visualStyle: 'Photorealistic cinematic video, realistic skin pore texture, natural eye micro-movements, cinematic depth of field.',
      negativeInstructions: [
        'Do not skip dialogue.',
        'Do not summarize dialogue.',
        'Do not paraphrase dialogue.',
        'Do not invent dialogue.',
        'Do not add dialogue.',
        'Do not change the dialogue.',
        'Do not make the character speak during silent sections.',
        'Do not create random voice-over.',
        'Do not change character identity.',
        'Do not morph the face.',
        'Do not distort the face.',
        'Do not distort hands.',
        'Do not create extra fingers.',
        'Do not create extra people.',
        'Do not create unwanted text.',
        'Do not create unwanted logos.',
        'Do not remove third-party watermarks.',
      ],
      generatedPrompt: '',
    },
    {
      id: 'sc-3',
      sceneNumber: 3,
      sceneLabel: 'SCENE 03',
      startTime: 14,
      endTime: 25,
      timeRangeStr: '00:14 — 00:25',
      durationSeconds: 11,
      durationFormatted: '11.0s',
      thumbnailUrl: '',
      subject: 'Om Gio emphasizing the strict unsummarized dialogue and lip-sync rule',
      character: 'Om Gio (Indonesian male, 28, slim fit, oval face, rectangular glasses, thin mustache, styled short black hair)',
      action: 'Om Gio squares up to the camera, bringing both hands up in an emphatic explanatory posture with fingers lightly curved, stressing the importance of exact speech transcription without dropping words.',
      bodyMovement: 'Slight upper body lean forward toward lens, expressive rhythmic hand gestures accentuating spoken cadence.',
      facialExpression: 'Deeply focused, earnest, authoritative, eyebrows slightly drawn in focus.',
      eyeDirection: 'Direct, unwavering eye contact with camera lens.',
      cameraAngle: 'Straight eye-level angle, intimate medium close-up.',
      cameraDistance: 'Medium close-up (chest up).',
      cameraMovement: 'Very slow, imperceptible dramatic push in (0.3m forward).',
      lensFeel: '50mm prime, ultra-sharp focus on eyeglass rims and eyes, soft background falloff.',
      composition: 'Symmetrical center-framed composition emphasizing authority and clarity.',
      environment: 'Ultra-modern tech creator studio with acoustic dark grey slatted wood panels and vertical cyan LED light channels.',
      background: 'Geometric acoustic baffles and vertical cyan light lines softly out of focus.',
      lighting: 'Bright, crisp key lighting highlighting facial expressions and natural skin sheen, rich shadows under jaw.',
      colorPalette: 'Monochrome charcoal, cool electric blue, warm honey skin highlights.',
      wardrobe: {
        shirt: 'Fitted charcoal black studio crewneck shirt',
        pants: 'Dark navy tailored slim-fit chinos',
        shoes: 'Minimalist white leather low-top sneakers',
        watch: 'Brushed stainless steel chronograph with black dial',
        glasses: 'Modern matte-black rectangular titanium frames',
        accessories: 'Subtle black wireless lavalier clip on collar',
      },
      props: 'Professional studio broadcast boom microphone visible in top-right periphery.',
      interaction: 'Synchronized hand gestures matching syllable cadence.',
      motion: 'Energetic, precise presenter gestures without jitter.',
      audioDescription: 'Very clean close-mic vocal presence, absolute zero room echo or distortion.',
      dialogueSegments: [
        {
          id: 'd-3',
          sceneId: 'sc-3',
          speaker: 'Om Gio',
          startTime: 14.6,
          endTime: 25.2,
          formattedStartTime: '00:14.60',
          formattedEndTime: '00:25.20',
          text: 'Kunci utamanya ada pada sinkronisasi audio dan dialog lengkap. Kita tidak boleh meringkas ucapan sedikit pun agar hasil lip-sync dan ekspresi di Veo tetap sempurna.',
          confidence: 0.99,
          language: 'Indonesian',
          emotion: 'emphatic, focused, serious',
          delivery: 'Firm articulate instruction, hands gesturing to screen monitor with purposeful emphasis',
        },
      ],
      dialogueTiming: 'Start: 00:14.60 | End: 00:25.20',
      voiceDelivery: 'Earnest, authoritative, instructional tone, steady rhythmic pacing.',
      lipSyncInstructions: 'Accurate lip synchronization with the supplied dialogue. Natural mouth movement. Natural jaw movement. Natural facial expression while speaking.',
      continuityNotes: 'Seamless continuity from Scene 02: eyeglasses position unchanged, hair styling intact, sleeve cuffs uniform.',
      visualStyle: 'Photorealistic cinematic video, realistic skin pore texture, natural eye micro-movements, cinematic depth of field.',
      negativeInstructions: [
        'Do not skip dialogue.',
        'Do not summarize dialogue.',
        'Do not paraphrase dialogue.',
        'Do not invent dialogue.',
        'Do not add dialogue.',
        'Do not change the dialogue.',
        'Do not make the character speak during silent sections.',
        'Do not create random voice-over.',
        'Do not change character identity.',
        'Do not morph the face.',
        'Do not distort the face.',
        'Do not distort hands.',
        'Do not create extra fingers.',
        'Do not create extra people.',
        'Do not create unwanted text.',
        'Do not create unwanted logos.',
        'Do not remove third-party watermarks.',
      ],
      generatedPrompt: '',
    },
    {
      id: 'sc-4',
      sceneNumber: 4,
      sceneLabel: 'SCENE 04',
      startTime: 25,
      endTime: 38,
      timeRangeStr: '00:25 — 00:38',
      durationSeconds: 13,
      durationFormatted: '13.0s',
      thumbnailUrl: '',
      subject: 'Om Gio discussing identity lock strength and facial features retention',
      character: 'Om Gio (Indonesian male, 28, slim fit, oval face, rectangular glasses, thin mustache, styled short black hair)',
      action: 'Om Gio smiles with confident satisfaction, taps the temple of his rectangular eyeglasses with his right forefinger lightly, demonstrating character facial lock consistency across the entire production.',
      bodyMovement: 'Head tilts subtly 5 degrees right, fluid hand touches glasses temple, relaxed natural posture.',
      facialExpression: 'Friendly, confident, subtle smile, warm crinkling around the eyes.',
      eyeDirection: 'Direct connection with viewer through the camera lens.',
      cameraAngle: 'Tight close-up shot, eye-level.',
      cameraDistance: 'Close-up (shoulders to forehead).',
      cameraMovement: 'Static locked camera on fluid tripod head.',
      lensFeel: '100mm macro/portrait lens, exquisite facial detail and realistic skin pores visible.',
      composition: 'Tightly framed portrait centered horizontally.',
      environment: 'Ultra-modern tech creator studio with acoustic dark grey slatted wood panels and vertical cyan LED light channels.',
      background: 'Soft cyan bokeh lights in background creating high-end studio depth.',
      lighting: 'Beauty ring/softbox frontal fill with delicate rim hair separation.',
      colorPalette: 'Dark navy, charcoal, cyan neon accents, warm natural tan skin tone.',
      wardrobe: {
        shirt: 'Fitted charcoal black studio crewneck shirt',
        pants: 'Dark navy tailored slim-fit chinos',
        shoes: 'Minimalist white leather low-top sneakers',
        watch: 'Brushed stainless steel chronograph with black dial',
        glasses: 'Modern matte-black rectangular titanium frames',
        accessories: 'Subtle black wireless lavalier clip on collar',
      },
      props: 'None directly in focus; pure portraiture emphasis.',
      interaction: 'Finger briefly points to glasses frame without dislodging it.',
      motion: 'Deliberate, relaxed, micro-gestures.',
      audioDescription: 'Rich broadcast vocal delivery, zero audible background hiss.',
      dialogueSegments: [
        {
          id: 'd-4',
          sceneId: 'sc-4',
          speaker: 'Om Gio',
          startTime: 25.8,
          endTime: 38.3,
          formattedStartTime: '00:25.80',
          formattedEndTime: '00:38.30',
          text: 'Perhatikan bagaimana konsistensi kacamata kotak, gaya rambut, dan proporsi wajah tetap terkunci di angka sembilan puluh lima persen di seluruh scene.',
          confidence: 0.97,
          language: 'Indonesian',
          emotion: 'confident, smiling, proud',
          delivery: 'Subtle friendly smile, leaning in toward camera with direct eye contact',
        },
      ],
      dialogueTiming: 'Start: 00:25.80 | End: 00:38.30',
      voiceDelivery: 'Warm, personable, confident Indonesian delivery with genuine creator excitement.',
      lipSyncInstructions: 'Accurate lip synchronization with the supplied dialogue. Natural mouth movement. Natural jaw movement. Natural facial expression while speaking.',
      continuityNotes: 'Identity lock at 95% enforced: facial hair, thin mustache, ear shape, nose bridge, rectangular glasses strictly preserved.',
      visualStyle: 'Photorealistic cinematic video, realistic skin pore texture, natural eye micro-movements, cinematic depth of field.',
      negativeInstructions: [
        'Do not skip dialogue.',
        'Do not summarize dialogue.',
        'Do not paraphrase dialogue.',
        'Do not invent dialogue.',
        'Do not add dialogue.',
        'Do not change the dialogue.',
        'Do not make the character speak during silent sections.',
        'Do not create random voice-over.',
        'Do not change character identity.',
        'Do not morph the face.',
        'Do not distort the face.',
        'Do not distort hands.',
        'Do not create extra fingers.',
        'Do not create extra people.',
        'Do not create unwanted text.',
        'Do not create unwanted logos.',
        'Do not remove third-party watermarks.',
      ],
      generatedPrompt: '',
    },
    {
      id: 'sc-5',
      sceneNumber: 5,
      sceneLabel: 'SCENE 05',
      startTime: 39,
      endTime: 54,
      timeRangeStr: '00:39 — 00:54',
      durationSeconds: 15,
      durationFormatted: '15.0s',
      thumbnailUrl: '',
      subject: 'Om Gio delivering call to action, closing outro, and farewell wave in the studio',
      character: 'Om Gio (Indonesian male, 28, slim fit, oval face, rectangular glasses, thin mustache, styled short black hair)',
      action: 'Om Gio stands tall, gestures toward the screen one final time, smiles widely, brings right hand up into a friendly farewell wave, then nods respectfully to the audience.',
      bodyMovement: 'Smooth full-body presence, fluid arm wave at chest height, confident posture.',
      facialExpression: 'Broad authentic smile, energetic, welcoming, warm closing expression.',
      eyeDirection: 'Direct friendly gaze right into camera lens.',
      cameraAngle: 'Medium wide shot, eye-level.',
      cameraDistance: 'Medium shot (thigh up).',
      cameraMovement: 'Cinematic slow pull-out (1.0m backward dolly tracking) revealing the full modern studio setup.',
      lensFeel: '35mm wide prime lens, expansive cinematic commercial field of view.',
      composition: 'Subject in golden center, framed symmetrically by slatted acoustic wall panels on both flanks.',
      environment: 'Ultra-modern tech creator studio with acoustic dark grey slatted wood panels and vertical cyan LED light channels.',
      background: 'Complete studio view showing workstation, dual monitors, studio lights on stands, and warm architectural wood slats.',
      lighting: 'Full cinematic studio illumination, warm key light, deep cyan architectural flood on back wall.',
      colorPalette: 'Cinematic deep blue, warm tungsten accents, graphite black, Indonesian skin glow.',
      wardrobe: {
        shirt: 'Fitted charcoal black studio crewneck shirt',
        pants: 'Dark navy tailored slim-fit chinos',
        shoes: 'Minimalist white leather low-top sneakers',
        watch: 'Brushed stainless steel chronograph with black dial',
        glasses: 'Modern matte-black rectangular titanium frames',
        accessories: 'Subtle black wireless lavalier clip on collar',
      },
      props: 'Full desk setup, wireless mouse, coffee mug, boom microphone.',
      interaction: 'Waves right hand toward viewer during outro words.',
      motion: 'Smooth graceful farewell motion, settling into a friendly pause at the end.',
      audioDescription: 'Dialogue loud and clear, background synth music gently swells +3dB for outro flourish.',
      dialogueSegments: [
        {
          id: 'd-5',
          sceneId: 'sc-5',
          speaker: 'Om Gio',
          startTime: 39.0,
          endTime: 53.5,
          formattedStartTime: '00:39.00',
          formattedEndTime: '00:53.50',
          text: 'Cukup salin prompt ini langsung ke Google Flow atau Veo, dan saksikan hasilnya. Jangan lupa like, subscribe, dan kita jumpa di video berikutnya!',
          confidence: 0.99,
          language: 'Indonesian',
          emotion: 'charismatic, warm, energetic outro',
          delivery: 'Warm enthusiastic closing tone, natural farewell wave gesture to camera',
        },
      ],
      dialogueTiming: 'Start: 00:39.00 | End: 00:53.50',
      voiceDelivery: 'Enthusiastic, charismatic Indonesian outro, bright friendly projection.',
      lipSyncInstructions: 'Accurate lip synchronization with the supplied dialogue. Natural mouth movement. Natural jaw movement. Natural facial expression while speaking. Mouth closes naturally after "berikutnya".',
      continuityNotes: 'Final scene concludes production arc with 100% continuity preserved across all 5 scenes.',
      visualStyle: 'Photorealistic cinematic video, realistic skin pore texture, natural eye micro-movements, cinematic depth of field.',
      negativeInstructions: [
        'Do not skip dialogue.',
        'Do not summarize dialogue.',
        'Do not paraphrase dialogue.',
        'Do not invent dialogue.',
        'Do not add dialogue.',
        'Do not change the dialogue.',
        'Do not make the character speak during silent sections.',
        'Do not create random voice-over.',
        'Do not change character identity.',
        'Do not morph the face.',
        'Do not distort the face.',
        'Do not distort hands.',
        'Do not create extra fingers.',
        'Do not create extra people.',
        'Do not create unwanted text.',
        'Do not create unwanted logos.',
        'Do not remove third-party watermarks.',
      ],
      generatedPrompt: '',
    },
  ],
};
