import { Project, SceneAnalysis, DialogueSegment, AudioEvent } from '../types';
import { generateGoogleFlowPrompt } from './promptGenerator';

/**
 * Adapts or trims a Project to strictly <= 11.0 seconds (Target: 10.5s),
 * perfectly formatted for Google Veo generation limits (10s max) and YouTube Shorts/TikTok.
 */
export function convertToUnder11SecondsStoryboard(project: Project): Project {
  const targetTotalDuration = 10.5;

  const shortScenes: SceneAnalysis[] = [
    {
      id: 'scene-01-short',
      sceneNumber: 1,
      sceneLabel: 'SCENE 01 (HOOK)',
      startTime: 0,
      endTime: 3,
      timeRangeStr: '00:00 — 00:03',
      durationSeconds: 3,
      durationFormatted: '3.0s',
      thumbnailUrl: '',
      omGioThumbnailUrl: '',
      subject: 'Om Gio opening hook in high-tech studio environment (00:00 — 00:03)',
      character: 'Om Gio (Indonesian male, 28, slim fit, oval face, rectangular glasses, thin mustache, styled short black hair)',
      action: 'Om Gio stands facing camera in his high-tech studio, smiling warmly as he welcomes the audience with natural relaxed posture.',
      bodyMovement: 'Natural weight distribution, smooth ergonomic gestures, stable upper torso posture.',
      facialExpression: 'Warm, approachable, confident smile, natural eye contact with camera lens.',
      eyeDirection: 'Direct center lock on camera lens, with natural gaze adjustments.',
      cameraAngle: 'Medium close-up shot, straight-on eye level.',
      cameraDistance: 'Medium close-up (chest to head).',
      cameraMovement: 'Static locked tripod shot with subtle cinematic stability.',
      lensFeel: '50mm prime cinematic lens, realistic natural perspective.',
      composition: 'Balanced golden ratio framing, ample subject headroom.',
      environment: 'Ultra-modern tech creator studio with acoustic dark grey slatted wood panels and vertical cyan LED light channels.',
      background: 'High-end workstation monitors and ambient architectural backlighting.',
      lighting: '3-point studio lighting: large softbox key light 45 degrees left, subtle warm fill right, vivid cyan-electric blue rim hair light.',
      colorPalette: 'Charcoal black, deep indigo, electric cyan accent, warm natural skin tones.',
      wardrobe: {
        shirt: 'Fitted charcoal black studio crewneck shirt',
        pants: 'Dark navy tailored slim-fit chinos',
        shoes: 'Minimalist white leather low-top sneakers',
        watch: 'Brushed stainless steel chronograph with black dial',
        glasses: 'Modern matte-black rectangular titanium frames',
        accessories: 'Subtle black wireless lavalier clip on collar',
      },
      props: 'Matte black studio desk, dynamic broadcast microphone on boom arm.',
      interaction: 'Subtle welcoming hand gesture toward camera.',
      motion: 'Smooth organic 24fps film motion cadence.',
      audioDescription: 'Clean studio acoustics, warm proximity effect on dialogue.',
      dialogueSegments: [
        {
          id: 'diag-01-short',
          sceneId: 'scene-01-short',
          speaker: 'Om Gio',
          speakerOriginal: 'Creator 1',
          startTime: 0.2,
          endTime: 2.8,
          formattedStartTime: '00:00.20',
          formattedEndTime: '00:02.80',
          text: 'Halo teman-teman semua, selamat datang di Om Gio AI Studio.',
          confidence: 0.99,
          language: 'Indonesian',
          emotion: 'friendly, welcoming, professional',
          delivery: 'Clear conversational Indonesian, upbeat intro cadence with crisp studio vocal projection',
        },
      ],
      dialogueTiming: 'Start: 00:00.20 | End: 00:02.80',
      voiceDelivery: 'Upbeat friendly Indonesian creator voice, articulate phrasing, warm resonant tone.',
      lipSyncInstructions: 'Accurate lip synchronization with Indonesian phonemes: Ha-lo te-man te-man se-mu-a... Natural mouth opening and relaxed jaw return.',
      continuityNotes: 'Scene 01 initiates identity baseline. Hair, glasses, watch, and studio layout establish master continuity reference.',
      visualStyle: 'Photorealistic cinematic video, realistic skin pore texture, natural eye micro-movements, cinematic depth of field.',
      negativeInstructions: [
        'Do not skip dialogue.',
        'Do not summarize dialogue.',
        'Do not paraphrase dialogue.',
        'Do not invent dialogue.',
        'Do not add dialogue.',
        'Do not change the dialogue.',
        'Do not make the character speak during silent sections.',
        'Do not create random voice-over.',
        'Do not change character identity.',
        'Do not morph the face.',
        'Do not distort the face.',
        'Do not distort hands.',
        'Do not create extra fingers.',
        'Do not create extra people.',
        'Do not create unwanted text.',
        'Do not create unwanted logos.',
        'Do not reproduce any logos, text overlays, or watermarks from original source video.',
        'Do not recreate foreign channel branding or third-party sponsor marks.',
      ],
      generatedPrompt: '',
    },
    {
      id: 'scene-02-short',
      sceneNumber: 2,
      sceneLabel: 'SCENE 02 (DEMO)',
      startTime: 3,
      endTime: 7,
      timeRangeStr: '00:03 — 00:07',
      durationSeconds: 4,
      durationFormatted: '4.0s',
      thumbnailUrl: '',
      omGioThumbnailUrl: '',
      subject: 'Om Gio demonstrating automated recreation workflow on display (00:03 — 00:07)',
      character: 'Om Gio (Indonesian male, 28, slim fit, oval face, rectangular glasses, thin mustache, styled short black hair)',
      action: 'Om Gio pivots slightly 20 degrees toward the workstation monitor, points smoothly toward the glowing AI pipeline timeline, then brings his eyes back to the camera lens.',
      bodyMovement: 'Fluid torso rotation, elegant hand gesture toward display, seamless transition.',
      facialExpression: 'Focused, articulate, professional tech authority with subtle enthusiastic brow lift.',
      eyeDirection: 'Looks at the monitor for 1 second, then locks eyes back with the camera lens.',
      cameraAngle: 'Medium-close shot, slight 15-degree side angle profile.',
      cameraDistance: 'Medium close-up (chest to head).',
      cameraMovement: 'Subtle slow slider truck right to left maintaining steady subject parallax.',
      lensFeel: '85mm portrait prime lens, creamy shallow depth of field isolating Om Gio from background glow.',
      composition: 'Left third rule of thirds composition leaving screen space on the right for studio visuals.',
      environment: 'Ultra-modern tech creator studio with acoustic dark grey slatted wood panels and vertical cyan LED light channels.',
      background: 'Glowing monitor showcasing video waveform timelines and AI prompt cards.',
      lighting: 'Controlled key lighting on face with vivid cyan edge rim light accentuating the jawline and glasses contour.',
      colorPalette: 'Deep navy, slate grey, neon cyan glow, natural warm Indonesian skin tone.',
      wardrobe: {
        shirt: 'Fitted charcoal black studio crewneck shirt',
        pants: 'Dark navy tailored slim-fit chinos',
        shoes: 'Minimalist white leather low-top sneakers',
        watch: 'Brushed stainless steel chronograph with black dial',
        glasses: 'Modern matte-black rectangular titanium frames',
        accessories: 'Subtle black wireless lavalier clip on collar',
      },
      props: 'Ultrawide curved production monitor, mechanical keyboard with subtle RGB backlight.',
      interaction: 'Points at the screen timeline interface without touching the display surface.',
      motion: 'Precise and confident presenter body dynamics.',
      audioDescription: 'Dialogue prioritized in center channel, crisp vocal projection.',
      dialogueSegments: [
        {
          id: 'diag-02-short',
          sceneId: 'scene-02-short',
          speaker: 'Om Gio',
          speakerOriginal: 'Creator 1',
          startTime: 3.2,
          endTime: 6.8,
          formattedStartTime: '00:03.20',
          formattedEndTime: '00:06.80',
          text: 'Kini rekreasikan seluruh video otomatis langsung dengan karakter dan gaya saya.',
          confidence: 0.98,
          language: 'Indonesian',
          emotion: 'articulate, authoritative, engaging',
          delivery: 'Structured tech presentation pacing, clear emphasis on key technical terminology',
        },
      ],
      dialogueTiming: 'Start: 00:03.20 | End: 00:06.80',
      voiceDelivery: 'Confident authoritative presenter voice, clean diction, articulate phrasing.',
      lipSyncInstructions: 'Accurate lip synchronization with Indonesian phonemes: Ki-ni re-kre-a-si-kan... Natural mouth movement.',
      continuityNotes: 'Wardrobe and lighting match Scene 01 perfectly, hair and glasses consistent.',
      visualStyle: 'Photorealistic cinematic video, realistic skin pore texture, natural eye micro-movements, cinematic depth of field.',
      negativeInstructions: [
        'Do not skip dialogue.',
        'Do not summarize dialogue.',
        'Do not paraphrase dialogue.',
        'Do not invent dialogue.',
        'Do not add dialogue.',
        'Do not change the dialogue.',
        'Do not make the character speak during silent sections.',
        'Do not create random voice-over.',
        'Do not change character identity.',
        'Do not morph the face.',
        'Do not distort the face.',
        'Do not distort hands.',
        'Do not create extra fingers.',
        'Do not create extra people.',
        'Do not create unwanted text.',
        'Do not create unwanted logos.',
        'Do not reproduce any logos, text overlays, or watermarks from original source video.',
        'Do not recreate foreign channel branding or third-party sponsor marks.',
      ],
      generatedPrompt: '',
    },
    {
      id: 'scene-03-short',
      sceneNumber: 3,
      sceneLabel: 'SCENE 03 (CTA)',
      startTime: 7,
      endTime: 10.5,
      timeRangeStr: '00:07 — 00:10.5',
      durationSeconds: 3.5,
      durationFormatted: '3.5s',
      thumbnailUrl: '',
      omGioThumbnailUrl: '',
      subject: 'Om Gio delivering call to action and closing outro (00:07 — 00:10.5)',
      character: 'Om Gio (Indonesian male, 28, slim fit, oval face, rectangular glasses, thin mustache, styled short black hair)',
      action: 'Om Gio faces camera directly with an engaging warm smile, gestures open-handed with genuine excitement, inviting the viewer to create.',
      bodyMovement: 'Upright confident presenter posture, natural welcoming hand gesture.',
      facialExpression: 'Broad authentic smile, energetic, welcoming, warm closing expression.',
      eyeDirection: 'Direct, unwavering eye contact with camera lens.',
      cameraAngle: 'Straight eye-level angle, intimate medium close-up.',
      cameraDistance: 'Medium close-up (chest up).',
      cameraMovement: 'Cinematic slow push in (0.2m forward) accentuating connection.',
      lensFeel: '50mm prime, ultra-sharp focus on eyeglass rims and eyes, soft background falloff.',
      composition: 'Symmetrical center-framed composition emphasizing authority and clarity.',
      environment: 'Ultra-modern tech creator studio with acoustic dark grey slatted wood panels and vertical cyan LED light channels.',
      background: 'Geometric acoustic baffles and vertical cyan light lines softly out of focus.',
      lighting: 'Bright, crisp key lighting highlighting facial expressions and natural skin sheen, rich shadows under jaw.',
      colorPalette: 'Monochrome charcoal, cool electric blue, warm honey skin highlights.',
      wardrobe: {
        shirt: 'Fitted charcoal black studio crewneck shirt',
        pants: 'Dark navy tailored slim-fit chinos',
        shoes: 'Minimalist white leather low-top sneakers',
        watch: 'Brushed stainless steel chronograph with black dial',
        glasses: 'Modern matte-black rectangular titanium frames',
        accessories: 'Subtle black wireless lavalier clip on collar',
      },
      props: 'Professional studio broadcast boom microphone visible in top-right periphery.',
      interaction: 'Synchronized hand gestures matching syllable cadence.',
      motion: 'Energetic, precise presenter gestures without jitter.',
      audioDescription: 'Very clean close-mic vocal presence, absolute zero room echo or distortion.',
      dialogueSegments: [
        {
          id: 'diag-03-short',
          sceneId: 'scene-03-short',
          speaker: 'Om Gio',
          speakerOriginal: 'Creator 1',
          startTime: 7.2,
          endTime: 10.2,
          formattedStartTime: '00:07.20',
          formattedEndTime: '00:10.20',
          text: 'Salin prompt ini ke Google Flow atau Veo, dan rasakan keajaibannya!',
          confidence: 0.99,
          language: 'Indonesian',
          emotion: 'charismatic, warm, energetic outro',
          delivery: 'Warm enthusiastic closing tone, natural farewell wave gesture to camera',
        },
      ],
      dialogueTiming: 'Start: 00:07.20 | End: 00:10.20',
      voiceDelivery: 'Earnest, authoritative, inspirational tone, steady rhythmic pacing.',
      lipSyncInstructions: 'Accurate lip synchronization with Indonesian phonemes: Sa-lin prompt i-ni ke Goo-gle Flow... Mouth closes naturally at completion.',
      continuityNotes: 'Final scene concludes production arc with 100% identity lock maintained.',
      visualStyle: 'Photorealistic cinematic video, realistic skin pore texture, natural eye micro-movements, cinematic depth of field.',
      negativeInstructions: [
        'Do not skip dialogue.',
        'Do not summarize dialogue.',
        'Do not paraphrase dialogue.',
        'Do not invent dialogue.',
        'Do not add dialogue.',
        'Do not change the dialogue.',
        'Do not make the character speak during silent sections.',
        'Do not create random voice-over.',
        'Do not change character identity.',
        'Do not morph the face.',
        'Do not distort the face.',
        'Do not distort hands.',
        'Do not create extra fingers.',
        'Do not create extra people.',
        'Do not create unwanted text.',
        'Do not create unwanted logos.',
        'Do not reproduce any logos, text overlays, or watermarks from original source video.',
        'Do not recreate foreign channel branding or third-party sponsor marks.',
      ],
      generatedPrompt: '',
    },
  ];

  // Generate prompts for all short scenes
  const updatedScenes = shortScenes.map((sc) => {
    sc.generatedPrompt = generateGoogleFlowPrompt(
      sc,
      project.character,
      project.recreationMode,
      project.videoMetadata?.aspectRatio || '16:9'
    );
    return sc;
  });

  const updatedTranscript: DialogueSegment[] = shortScenes.flatMap(
    (sc) => sc.dialogueSegments || []
  );

  const updatedAudioEvents: AudioEvent[] = [
    {
      id: 'ae-short-1',
      type: 'dialogue',
      label: 'Spoken Dialogue (Intro Hook)',
      startTime: 0.2,
      endTime: 2.8,
      formattedRange: '00:00.20 — 00:02.80',
      description: 'Om Gio greeting in clean studio acoustic environment.',
      intensity: 'high',
    },
    {
      id: 'ae-short-2',
      type: 'music',
      label: 'Background Ambient Lo-Fi Synth',
      startTime: 0.0,
      endTime: targetTotalDuration,
      formattedRange: '00:00.00 — 00:10.50',
      description: 'Subtle modern tech synth pad sitting at -24dB beneath dialogue.',
      intensity: 'low',
    },
    {
      id: 'ae-short-3',
      type: 'dialogue',
      label: 'Spoken Dialogue (Core Demo)',
      startTime: 3.2,
      endTime: 6.8,
      formattedRange: '00:03.20 — 00:06.80',
      description: 'Explanation of automated video recreation.',
      intensity: 'high',
    },
    {
      id: 'ae-short-4',
      type: 'dialogue',
      label: 'Spoken Dialogue (Call to Action)',
      startTime: 7.2,
      endTime: 10.2,
      formattedRange: '00:07.20 — 00:10.20',
      description: 'Closing call-to-action for Google Flow / Veo generation.',
      intensity: 'high',
    },
  ];

  return {
    ...project,
    videoMetadata: {
      ...(project.videoMetadata || {}),
      duration: targetTotalDuration,
      durationFormatted: '00:00:10.5',
      audioDuration: '00:00:10.5',
      totalFrames: 315,
      filename: project.videoMetadata?.filename || 'omgio_short_recreation_10.5s.mp4',
      resolutionFormatted: project.videoMetadata?.resolutionFormatted || '1920 × 1080',
      fps: 30,
      fileSize: '12.4 MB',
      aspectRatio: project.videoMetadata?.aspectRatio || '16:9',
      codec: 'H.264 / AVC',
      audioCodec: 'AAC-LC (Stereo, 48.0 kHz)',
      audioChannels: '2 (Stereo)',
      audioDetected: true,
      width: project.videoMetadata?.width || 1920,
      height: project.videoMetadata?.height || 1080,
    },
    stats: {
      totalDuration: targetTotalDuration,
      totalDurationStr: '00:00:10.5',
      speechDuration: 9.8,
      speechDurationStr: '00:00:09.8',
      speakerCount: 1,
      dialogueCount: 3,
      wordCount: 32,
      unclearCount: 0,
      unmappedCount: 0,
      sceneCount: 3,
      promptsGeneratedCount: 3,
    },
    scenes: updatedScenes,
    transcript: updatedTranscript,
    audioEvents: updatedAudioEvents,
    updatedAt: new Date().toISOString(),
  };
}
